/*
  PostTrig.h: Read and format the waveform traces generated by the 6022 'scope.

  Copyright (C) 2018 P G Duesbury

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/


#ifndef POSTTRIG_H
#define POSTTRIG_H

#ifdef __cplusplus
 extern "C" {
#endif

extern int get_post_trigger_waveforms
(
  double* y1_vec,                                    // QVector<double> &y1_vec,
  double* y2_vec,                                    // QVector<double> &y2_vec,
  double* x_vec,                                      // QVector<double> &x_vec,
  unsigned char* CH0,                          // interleaved waveforms from USB
  DSO_CHANNEL* Channel1,
  DSO_CHANNEL* Channel2,
  int TriggerPoint,                             // initial trigger edge position
  int TriggerEdge                                           // rising or falling
);

#ifdef __cplusplus
    }
#endif

#endif // POSTTRIG_H
